# Generated by Django 4.2.30 on 2026-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('APPROVER', 'Approver'), ('AGENT', 'Support Team'), ('END_USER', 'User')], default='END_USER', max_length=20),
        ),
    ]
