# Generated by Django 4.2.18 on 2026-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_ticket_view',
            field=models.CharField(choices=[('list', 'List'), ('kanban', 'Kanban')], default='list', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for ticket updates'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='in_app_notifications',
            field=models.BooleanField(default=True, help_text='Receive in-app notifications (bell icon)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ticket_signature',
            field=models.TextField(blank=True, help_text='Default signature for ticket replies (plain text)'),
        ),
    ]
