# Generated by Django 4.2.18 on 2026-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_default_ticket_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('AGENT', 'Support Team'), ('END_USER', 'User')], default='END_USER', max_length=20),
        ),
    ]
