# Generated by Django 4.2.18 on 2026-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TICKET', 'Ticket'), ('REMOTE_SESSION', 'Remote Session'), ('MANAGER_REVIEW', 'Manager Review'), ('APPROVAL', 'Approval')], default='GENERAL', max_length=20),
        ),
    ]
