# Generated by Django 4.2.30 on 2026-06-04 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workdays', models.JSONField(default=list)),
                ('work_start', models.TimeField(default=datetime.time(8, 0))),
                ('work_end', models.TimeField(default=datetime.time(18, 0))),
                ('holidays', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low')], max_length=2)),
                ('timer_type', models.CharField(choices=[('response', 'Response'), ('resolution', 'Resolution')], max_length=20)),
                ('threshold_percent', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('notify', 'Notify'), ('reassign', 'Reassign'), ('add_watcher', 'Add Watcher')], max_length=20)),
                ('notify_role', models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('APPROVER', 'Approver'), ('AGENT', 'Agent'), ('END_USER', 'End User')], max_length=20, null=True)),
                ('reassign_to_role', models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('APPROVER', 'Approver'), ('AGENT', 'Agent'), ('END_USER', 'End User')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low')], max_length=2, unique=True)),
                ('response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.businesscalendar')),
            ],
        ),
    ]
