# Generated by Django 4.2.30 on 2026-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_businesscalendar_escalationrule_sla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='notify_role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('APPROVER', 'Approver'), ('AGENT', 'Support Team'), ('END_USER', 'User')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='reassign_to_role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('APPROVER', 'Approver'), ('AGENT', 'Support Team'), ('END_USER', 'User')], max_length=20, null=True),
        ),
    ]
