# Generated by Django 4.2.30 on 2026-06-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remoteconnector_remotesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotesession',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('STARTED', 'Started'), ('ENDED', 'Ended'), ('EXPIRED', 'Expired')], default='REQUESTED', max_length=20),
        ),
    ]
