# Generated by Django 4.2.18 on 2026-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_remotesession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_USER', 'Pending User'), ('PENDING_VENDOR', 'Pending Vendor'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='NEW', max_length=20),
        ),
    ]
