# Generated by Django 4.2.18 on 2026-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('REASSIGN_REASON', 'Reassign Reason'), ('RETURN_REASON', 'Return Reason')], default='COMMENT', max_length=20),
        ),
    ]
