# Generated by Django 4.2.18 on 2026-06-29 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_macro_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to_department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='scrap_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='scrap_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='scrap_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scraps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='tracking_id',
            field=models.CharField(default=None, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_STORE', 'In Store'), ('MAINTENANCE', 'Maintenance'), ('DAMAGED', 'Damaged'), ('SCRAPPED', 'Scrapped'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status Changed'), ('SCRAP_REQUESTED', 'Scrap Requested'), ('SCRAP_APPROVED', 'Scrap Approved'), ('SCRAP_REJECTED', 'Scrap Rejected')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tickets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
