# Generated by Django 4.2.18 on 2026-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_asset_assigned_to_department_asset_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
