# Generated by Django 4.2.18 on 2026-06-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_asset_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tracking_id',
        ),
    ]
