# Generated by Django 4.2.18 on 2026-06-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_asset_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tracking_id',
            field=models.CharField(default=3004, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
