# Generated by Django 4.2.18 on 2026-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_asset_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warranty_duration_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='Warranty duration in years'),
        ),
    ]
