# Generated by Django 4.2.18 on 2026-07-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, choices=[('HQ', 'Headquarters'), ('BRANCH_A', 'Branch A - Lagos'), ('BRANCH_B', 'Branch B - Abuja'), ('BRANCH_C', 'Branch C - Port Harcourt'), ('WAREHOUSE', 'Warehouse'), ('DATA_CENTER', 'Data Center'), ('OTHER', 'Other')], default='HQ', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_STORE', 'In Store'), ('MAINTENANCE', 'Maintenance'), ('DAMAGED', 'Damaged'), ('SCRAPPED', 'Scrapped'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], default='ACTIVE', max_length=20),
        ),
    ]
