# Generated by Django 4.2.18 on 2026-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_add_location_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(default='COMPUTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, default='HQ', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
