# Generated by Django 4.2.18 on 2026-07-04 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0020_alter_asset_asset_type_alter_asset_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.asset'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_asset_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_USER', 'Pending User'), ('PENDING_VENDOR', 'Pending Vendor'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING_MANAGER_REVIEW', 'Pending Manager Review'), ('PENDING_FULFILLMENT', 'Pending Fulfillment'), ('APPROVED', 'Approved'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='NEW', max_length=30),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_asset_request'], name='tickets_tic_status_8945d8_idx'),
        ),
    ]
