# Generated by Django 4.2.18 on 2026-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticket_assigned_asset_ticket_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='notify_role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('AGENT', 'Support Team'), ('END_USER', 'User')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='reassign_to_role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('AGENT', 'Support Team'), ('END_USER', 'User')], max_length=20, null=True),
        ),
    ]
